name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4  # Adjust the version if necessary
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Updated to Python 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI Server
      run: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
      env:
        PORT: 8000

    - name: Wait for server to start
      run: sleep 5

    - name: Run Tests
      run: |
        pytest

    - name: Stop FastAPI Server
      run: |
        pkill -f uvicorn
